[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture amd64",
    "apt-get update && apt-get install -y libasound2-dev libx11-dev libxcb1-dev libxkbcommon-dev libwayland-dev"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install -y libasound2-dev:arm64 libx11-dev:arm64 libxcb1-dev:arm64 libxkbcommon-dev:arm64 libwayland-dev:arm64"
]
